
stages:
  - build
  - deploy

variables:
  NODE_VERSION: "18"

# Build job
build:
  stage: build
  image: node:${NODE_VERSION}
  cache:
    paths:
      - node_modules/
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour
  only:
    - main

# Deploy to GitLab Pages
pages:
  stage: deploy
  image: alpine:latest
  dependencies:
    - build
  script:
    - mkdir public
    - cp -r dist/* public/
  artifacts:
    paths:
      - public
  only:
    - main
